
package cn.org;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>火车时刻表 WEB 服务</strong>提供：站站查询；车次查询；车站所有车次查询。本火车时刻表 WEB 服务提供的列车时刻表数据仅供参考，如有异议以当地铁路部门颁布为准。</br>此火车时刻表Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrainTimeWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://ws.webxml.com.cn/WebServices/TrainTimeWebService.asmx?wsdl")
public class TrainTimeWebService
    extends Service
{

    private final static URL TRAINTIMEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAINTIMEWEBSERVICE_EXCEPTION;
    private final static QName TRAINTIMEWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "TrainTimeWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.webxml.com.cn/WebServices/TrainTimeWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAINTIMEWEBSERVICE_WSDL_LOCATION = url;
        TRAINTIMEWEBSERVICE_EXCEPTION = e;
    }

    public TrainTimeWebService() {
        super(__getWsdlLocation(), TRAINTIMEWEBSERVICE_QNAME);
    }

    public TrainTimeWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAINTIMEWEBSERVICE_QNAME, features);
    }

    public TrainTimeWebService(URL wsdlLocation) {
        super(wsdlLocation, TRAINTIMEWEBSERVICE_QNAME);
    }

    public TrainTimeWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAINTIMEWEBSERVICE_QNAME, features);
    }

    public TrainTimeWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrainTimeWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrainTimeWebServiceSoap
     */
    @WebEndpoint(name = "TrainTimeWebServiceSoap")
    public TrainTimeWebServiceSoap getTrainTimeWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "TrainTimeWebServiceSoap"), TrainTimeWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainTimeWebServiceSoap
     */
    @WebEndpoint(name = "TrainTimeWebServiceSoap")
    public TrainTimeWebServiceSoap getTrainTimeWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "TrainTimeWebServiceSoap"), TrainTimeWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAINTIMEWEBSERVICE_EXCEPTION!= null) {
            throw TRAINTIMEWEBSERVICE_EXCEPTION;
        }
        return TRAINTIMEWEBSERVICE_WSDL_LOCATION;
    }

}
